import {
  type BaseItemDefinition,
  type AffixDefinition,
  type RarityConfig,
  Rarity,
  StatType,
  EquipSlot,
} from './itemTypes';

// ===================================
// レアリティ設定
// ===================================
export const RARITY_CONFIG: Record<Rarity, RarityConfig> = {
  [Rarity.Common]: { name: 'Common', nameJa: 'コモン', color: '#94a3b8', totalAffixCount: 0, dropWeight: 1000 },
  [Rarity.Uncommon]: { name: 'Uncommon', nameJa: 'アンコモン', color: '#4ade80', totalAffixCount: 1, dropWeight: 400 },
  [Rarity.Magic]: { name: 'Magic', nameJa: 'マジック', color: '#60a5fa', totalAffixCount: 2, dropWeight: 160 },
  [Rarity.Rare]: { name: 'Rare', nameJa: 'レア', color: '#fbbf24', totalAffixCount: 3, dropWeight: 64 },
  [Rarity.Epic]: { name: 'Epic', nameJa: 'エピック', color: '#a78bfa', totalAffixCount: 4, dropWeight: 25.6 },
  [Rarity.Legendary]: { name: 'Legendary', nameJa: 'レジェンダリー', color: '#f97316', totalAffixCount: 5, dropWeight: 10.24 },
  [Rarity.Mythic]: { name: 'Mythic', nameJa: 'ミシック', color: '#ef4444', totalAffixCount: 6, dropWeight: 4.096 },
  [Rarity.Immortal]: { name: 'Immortal', nameJa: 'イモータル', color: '#d946ef', totalAffixCount: 7, dropWeight: 1.6384 },
  [Rarity.Celestial]: { name: 'Celestial', nameJa: 'セレスティアル', color: '#f8fafc', totalAffixCount: 8, dropWeight: 0.65536 },
};

// ===================================
// ベースアイテム マスターデータ
// ===================================
// ===================================
// ベースアイテム マスターデータ
// ===================================
export const BASE_ITEMS: readonly BaseItemDefinition[] = [
  // --- 近接武器 (Melee) ---
  {
    id: 'dagger',
    name: 'Dagger',
    nameJa: 'ダガー',
    slot: EquipSlot.MeleeWeapon,
    attackType: 'melee',
    baseStats: [{ stat: StatType.MeleeAttack, value: 1 }],
    attackInterval: 0.4,
    meleeWidth: 2.0,
    meleeRange: 0.15,
    pierceDecay: 0.125,
    shootSound: 'swing_dagger',
    hitSound: 'hit_dagger',
    moveSpeedMultiplier: 0.90,
  },
  {
    id: 'saber',
    name: 'Saber',
    nameJa: 'セイバー',
    slot: EquipSlot.MeleeWeapon,
    attackType: 'melee',
    baseStats: [{ stat: StatType.MeleeAttack, value: 1 }],
    attackInterval: 0.8,
    meleeWidth: 4.0,
    meleeRange: 0.25,
    pierceDecay: 0.08,
    shootSound: 'swing_saber',
    hitSound: 'hit_saber',
    moveSpeedMultiplier: 0.85,
  },
  {
    id: 'axe',
    name: 'Axe',
    nameJa: 'アックス',
    slot: EquipSlot.MeleeWeapon,
    attackType: 'melee',
    baseStats: [{ stat: StatType.MeleeAttack, value: 1 }],
    attackInterval: 1.2,
    attackStyle: 'vertical_slash', // 縦斬りエフェクト「十戒」
    meleeWidth: 6.0, // 波紋の広がり幅
    meleeRange: 0.2,
    pierceDecay: 0.05,
    shootSound: 'swing_axe',
    hitSound: 'hit_axe',
    moveSpeedMultiplier: 0.80,
  },
  {
    id: 'spear',
    name: 'Spear',
    nameJa: 'スピア',
    slot: EquipSlot.MeleeWeapon,
    attackType: 'melee',
    baseStats: [{ stat: StatType.MeleeAttack, value: 1 }],
    attackInterval: 0.6,
    meleeWidth: 1.0,
    meleeRange: 0.4,
    pierceDecay: 0.1,
    shootSound: 'swing_spear',
    hitSound: 'hit_spear',
    moveSpeedMultiplier: 0.85,
  },
  {
    id: 'claymore',
    name: 'Claymore',
    nameJa: 'クレイモア',
    slot: EquipSlot.MeleeWeapon,
    attackType: 'melee',
    baseStats: [{ stat: StatType.MeleeAttack, value: 1 }],
    attackInterval: 1.6,
    attackStyle: 'sweep',
    meleeWidth: 8.0,
    meleeRange: 0.35,
    pierceDecay: 0.04,
    shootSound: 'swing_claymore',
    hitSound: 'hit_claymore',
    moveSpeedMultiplier: 0.80,
  },
  {
    id: 'hammer',
    name: 'Hammer',
    nameJa: 'ハンマー',
    slot: EquipSlot.MeleeWeapon,
    attackType: 'melee',
    baseStats: [{ stat: StatType.MeleeAttack, value: 1 }],
    attackInterval: 2.0,
    attackStyle: 'slam',
    meleeWidth: 12.0,
    meleeRange: 0.2,
    pierceDecay: 0.03,
    shootSound: 'swing_hammer',
    hitSound: 'hit_hammer',
    moveSpeedMultiplier: 0.75,
  },
  {
    id: 'knuckle',
    name: 'Knuckle',
    nameJa: 'ナックル',
    slot: EquipSlot.MeleeWeapon,
    attackType: 'melee',
    baseStats: [{ stat: StatType.MeleeAttack, value: 1 }],
    attackInterval: 0.2,
    attackStyle: 'punch',
    meleeWidth: 1.0,
    meleeRange: 0.1,
    pierceDecay: 0.2,
    shootSound: 'swing_knuckle',
    hitSound: 'hit_knuckle',
    moveSpeedMultiplier: 0.95,
  },
  {
    id: 'kris',
    name: 'Kris',
    nameJa: 'クリス',
    slot: EquipSlot.MeleeWeapon,
    attackType: 'melee',
    baseStats: [{ stat: StatType.MeleeAttack, value: 0.5 }, { stat: StatType.MagicPower, value: 0.5 }],
    attackInterval: 0.5,
    meleeWidth: 1.6,
    meleeRange: 0.12,
    pierceDecay: 0.125,
    shootSound: 'swing_kris',
    hitSound: 'hit_kris',
    moveSpeedMultiplier: 0.95,
  },
  {
    id: 'mace',
    name: 'Rune Mace',
    nameJa: 'ルーンメイス',
    slot: EquipSlot.MeleeWeapon,
    attackType: 'melee',
    baseStats: [{ stat: StatType.MeleeAttack, value: 0.5 }, { stat: StatType.MagicPower, value: 0.5 }],
    attackInterval: 2.5,
    attackStyle: 'slam',
    meleeWidth: 9.6,
    meleeRange: 0.16,
    pierceDecay: 0.03,
    shootSound: 'swing_mace',
    hitSound: 'hit_mace',
    moveSpeedMultiplier: 0.90,
  },
  {
    id: 'gauntlet',
    name: 'Gauntlet',
    nameJa: 'ガントレット',
    slot: EquipSlot.MeleeWeapon,
    attackType: 'melee',
    baseStats: [{ stat: StatType.MeleeAttack, value: 0.5 }, { stat: StatType.MagicPower, value: 0.5 }],
    attackInterval: 0.25,
    attackStyle: 'punch',
    meleeWidth: 1.0,
    meleeRange: 0.08,
    pierceDecay: 0.2,
    visualScale: 0.8,
    shootSound: 'swing_gauntlet',
    hitSound: 'hit_gauntlet',
    moveSpeedMultiplier: 1.00,
  },

  // --- 遠距離武器 (Ranged) ---
  {
    id: 'handgun',
    name: 'Handgun',
    nameJa: 'ハンドガン',
    slot: EquipSlot.RangedWeapon,
    attackType: 'ranged',
    baseStats: [{ stat: StatType.RangedAttack, value: 1 }],
    attackInterval: 0.4, // 追加: 基本的な連射速度
    projectileSpeed: 25.0,
    projectileCount: 1,
    pierceCount: 2,
    lifespan: 0.5,
    shootSound: 'shoot_handgun',
    hitSound: 'hit_handgun',
    moveSpeedMultiplier: 0.90,
  },
  {
    id: 'smg', // 新規追加
    name: 'SMG',
    nameJa: 'サブマシンガン',
    slot: EquipSlot.RangedWeapon,
    attackType: 'ranged',
    baseStats: [{ stat: StatType.RangedAttack, value: 1 }],
    attackInterval: 0.2, // 超高速連射
    projectileSpeed: 20.0,
    projectileCount: 1,
    spreadAngle: 0.1, // 少しバラける
    pierceCount: 1,
    lifespan: 0.35,
    shootSound: 'shoot_smg',
    hitSound: 'hit_smg',
    moveSpeedMultiplier: 0.80,
  },
  {
    id: 'rifle', // スナイパーの役割を統合
    name: 'Rifle',
    nameJa: 'ライフル',
    slot: EquipSlot.RangedWeapon,
    attackType: 'ranged',
    baseStats: [{ stat: StatType.RangedAttack, value: 1 }],
    attackInterval: 1.0, // 射撃間隔を短縮
    projectileSpeed: 50.0,
    projectileCount: 1,
    pierceCount: 5, // 最大ヒット数を減少
    lifespan: 0.8,
    shootSound: 'shoot_rifle',
    hitSound: 'hit_rifle',
    moveSpeedMultiplier: 0.75,
  },
  {
    id: 'shotgun',
    name: 'Shotgun',
    nameJa: 'ショットガン',
    slot: EquipSlot.RangedWeapon,
    attackType: 'ranged',
    baseStats: [{ stat: StatType.RangedAttack, value: 1 }],
    attackInterval: 1.2,
    projectileSpeed: 16.0,
    projectileCount: 5, // 3発から5発へ増量
    spreadAngle: 0.35,
    pierceCount: 1,
    lifespan: 0.4,
    shootSound: 'shoot_shotgun',
    hitSound: 'hit_shotgun',
    moveSpeedMultiplier: 0.80,
  },
  {
    id: 'grenade_launcher', // 新規追加
    name: 'Grenade Launcher',
    nameJa: 'グレネードランチャー',
    slot: EquipSlot.RangedWeapon,
    attackType: 'ranged',
    baseStats: [{ stat: StatType.RangedAttack, value: 1 }],
    attackInterval: 2.0,
    projectileSpeed: 12.0, // 弾速を2倍に（飛距離維持）
    projectileCount: 1,
    pierceCount: 1, // 当たったら即消滅(爆発)
    lifespan: 0.5,
    attackStyle: 'grenade', // 変更
    pierceDecay: 0.03,      // 元に戻しました
    shootSound: 'shoot_grenade',
    hitSound: 'hit_grenade',
    moveSpeedMultiplier: 0.70,
  },
  {
    id: 'boomerang',
    name: 'Boomerang',
    nameJa: 'ブーメラン',
    slot: EquipSlot.RangedWeapon,
    attackType: 'ranged',
    baseStats: [{ stat: StatType.RangedAttack, value: 1 }],
    attackInterval: 0.8,
    projectileSpeed: 20.0,
    projectileCount: 1,
    pierceCount: 999,
    lifespan: 1.5,
    attackStyle: 'boomerang',
    pierceDecay: 0.1,       // 元に戻しました
    shootSound: 'shoot_boomerang',
    hitSound: 'hit_boomerang',
    moveSpeedMultiplier: 0.85,
  },
  {
    id: 'chakram',
    name: 'Chakram',
    nameJa: 'チャクラム',
    slot: EquipSlot.RangedWeapon,
    attackType: 'ranged',
    baseStats: [{ stat: StatType.RangedAttack, value: 1 }],
    attackInterval: 2.0,     // 3秒間隔で展開
    projectileSpeed: 5.0,      // 自力での前進はしないが回転速度として使用
    projectileCount: 2,      // デフォルトで2つの刃が回る
    spreadAngle: 3.1415,     // 180度反対方向に展開
    pierceCount: 999,
    lifespan: 2.0,           // 3秒間回り続ける(実質常時展開)
    attackStyle: 'orbit',
    pierceDecay: 0.1,
    shootSound: 'shoot_chakram',
    hitSound: 'hit_chakram',
    moveSpeedMultiplier: 0.75,
  },
  {
    id: 'grimoire',
    name: 'Grimoire',
    nameJa: 'グリモワール',
    slot: EquipSlot.RangedWeapon,
    attackType: 'ranged',
    baseStats: [{ stat: StatType.RangedAttack, value: 0.5 }, { stat: StatType.MagicPower, value: 0.5 }],
    attackInterval: 2.0,
    projectileSpeed: 8.0, 
    projectileCount: 1,
    pierceCount: 8,
    lifespan: 4.0,
    isHoming: true,
    homingPower: 5.0,
    shootSound: 'shoot_grimoire',
    hitSound: 'hit_grimoire',
    moveSpeedMultiplier: 0.95,
  },
  {
    id: 'cards',
    name: 'Magic Cards',
    nameJa: 'マジックカード',
    slot: EquipSlot.RangedWeapon,
    attackType: 'ranged',
    baseStats: [{ stat: StatType.RangedAttack, value: 0.5 }, { stat: StatType.MagicPower, value: 0.5 }],
    attackInterval: 1.5,
    projectileSpeed: 11.2,
    projectileCount: 5,
    spreadAngle: 0.5, 
    pierceCount: 1,
    lifespan: 0.5,
    shootSound: 'shoot_cards',
    hitSound: 'hit_cards',
    moveSpeedMultiplier: 1.00,
  },
  {
    id: 'orb',
    name: 'Orb',
    nameJa: 'オーブ',
    slot: EquipSlot.RangedWeapon,
    attackType: 'ranged',
    baseStats: [{ stat: StatType.RangedAttack, value: 0.5 }, { stat: StatType.MagicPower, value: 0.5 }],
    attackInterval: 2.5,
    projectileSpeed: 4.0, // 回転速度として使用
    projectileCount: 2, 
    spreadAngle: 3.1415,
    pierceCount: 999,
    lifespan: 2.0,
    attackStyle: 'orbit', 
    pierceDecay: 0.1,
    visualScale: 0.8,
    shootSound: 'shoot_orb',
    hitSound: 'hit_orb',
    moveSpeedMultiplier: 0.90,
  },

  // --- 防具・アクセサリー ---
  {
    id: 'shield',
    name: 'Shield',
    nameJa: 'シールド',
    slot: EquipSlot.Shield,
    attackType: 'none',
    baseStats: [{ stat: StatType.Evasion, value: 0.5 }],
  },
  {
    id: 'armor',
    name: 'Armor',
    nameJa: 'アーマー',
    slot: EquipSlot.Armor,
    attackType: 'none',
    baseStats: [{ stat: StatType.Defense, value: 1 }],
  },
  {
    id: 'helm',
    name: 'Helm',
    nameJa: 'ヘルム',
    slot: EquipSlot.Helmet,
    attackType: 'none',
    baseStats: [{ stat: StatType.Health, value: 1 }],
  },
  {
    id: 'boots',
    name: 'Boots',
    nameJa: 'ブーツ',
    slot: EquipSlot.Boots,
    attackType: 'none',
    baseStats: [{ stat: StatType.Speed, value: 1 }],
  },
  {
    id: 'ring',
    name: 'Ring',
    nameJa: 'リング',
    slot: EquipSlot.Ring,
    attackType: 'none',
    baseStats: [{ stat: StatType.PickupRange, value: 1 }],
  },
  {
    id: 'amulet',
    name: 'Amulet',
    nameJa: 'アミュレット',
    slot: EquipSlot.Amulet,
    attackType: 'none',
    baseStats: [{ stat: StatType.HpRegen, value: 0.01 }],
  },
];

// ===================================
// 接頭辞（Prefix）マスターデータ
// ===================================
export const PREFIX_POOL: readonly AffixDefinition[] = [
  { id: 'pre_health', name: 'Health', nameJa: '生命の', type: 'prefix', requiredItemLevel: 1, modifiers: [{ stat: StatType.Health, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'pre_melee', name: 'Melee', nameJa: '剛力の', type: 'prefix', requiredItemLevel: 1, modifiers: [{ stat: StatType.MeleeAttack, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'pre_ranged', name: 'Ranged', nameJa: '射手の', type: 'prefix', requiredItemLevel: 1, modifiers: [{ stat: StatType.RangedAttack, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'pre_magic', name: 'Magic', nameJa: '魔導の', type: 'prefix', requiredItemLevel: 1, modifiers: [{ stat: StatType.MagicPower, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'pre_crit', name: 'Crit', nameJa: '必殺の', type: 'prefix', requiredItemLevel: 1, modifiers: [{ stat: StatType.CritChance, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'pre_def', name: 'Defense', nameJa: '頑丈な', type: 'prefix', requiredItemLevel: 1, modifiers: [{ stat: StatType.Defense, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'pre_eva', name: 'Insight', nameJa: '見切りの', type: 'prefix', requiredItemLevel: 1, modifiers: [{ stat: StatType.Evasion, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'pre_speed', name: 'Speed', nameJa: '迅速な', type: 'prefix', requiredItemLevel: 1, modifiers: [{ stat: StatType.Speed, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'pre_greedy', name: 'Greed', nameJa: '強欲な', type: 'prefix', requiredItemLevel: 1, modifiers: [{ stat: StatType.PickupRange, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'pre_regen', name: 'Regen', nameJa: '癒やしの', type: 'prefix', requiredItemLevel: 1, modifiers: [{ stat: StatType.HpRegen, minValue: 1, maxValue: 25, isPercentage: true }] },
];

// ===================================
// 接尾辞（Suffix）マスターデータ
// ===================================
export const SUFFIX_POOL: readonly AffixDefinition[] = [
  { id: 'suf_health', name: 'Life', nameJa: '〜の活力', type: 'suffix', requiredItemLevel: 1, modifiers: [{ stat: StatType.Health, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'suf_melee', name: 'Strength', nameJa: '〜の腕力', type: 'suffix', requiredItemLevel: 1, modifiers: [{ stat: StatType.MeleeAttack, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'suf_ranged', name: 'Snipe', nameJa: '〜の狙撃', type: 'suffix', requiredItemLevel: 1, modifiers: [{ stat: StatType.RangedAttack, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'suf_magic', name: 'Wisdom', nameJa: '〜の知恵', type: 'suffix', requiredItemLevel: 1, modifiers: [{ stat: StatType.MagicPower, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'suf_crit', name: 'Precision', nameJa: '〜の精密', type: 'suffix', requiredItemLevel: 1, modifiers: [{ stat: StatType.CritChance, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'suf_def', name: 'Guard', nameJa: '〜の守護', type: 'suffix', requiredItemLevel: 1, modifiers: [{ stat: StatType.Defense, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'suf_eva', name: 'Parry', nameJa: '〜の受け流し', type: 'suffix', requiredItemLevel: 1, modifiers: [{ stat: StatType.Evasion, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'suf_speed', name: 'Gale', nameJa: '〜の疾風', type: 'suffix', requiredItemLevel: 1, modifiers: [{ stat: StatType.Speed, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'suf_greedy', name: 'Attraction', nameJa: '〜の引力', type: 'suffix', requiredItemLevel: 1, modifiers: [{ stat: StatType.PickupRange, minValue: 1, maxValue: 25, isPercentage: true }] },
  { id: 'suf_regen', name: 'Regen', nameJa: '〜の再生', type: 'suffix', requiredItemLevel: 1, modifiers: [{ stat: StatType.HpRegen, minValue: 1, maxValue: 25, isPercentage: true }] },
];
